package modelo;
// Generated 22:38:40, 2 de feb. de 2023 by Hibernate Tools 6.1.5.Final

import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * AccMovement generated by hbm2java
 */
public class AccMovement implements java.io.Serializable {

	private Integer accountMovId;
	private Account accountByAccountDestId;
	private Account accountByAccountOriginId;
	private BigDecimal amount;
	private Timestamp datetime;

	public AccMovement() {
	}

	public AccMovement(Account accountByAccountDestId, Account accountByAccountOriginId, BigDecimal amount,
			Timestamp datetime) {
		this.accountByAccountDestId = accountByAccountDestId;
		this.accountByAccountOriginId = accountByAccountOriginId;
		this.amount = amount;
		this.datetime = datetime;
	}

	public Integer getAccountMovId() {
		return this.accountMovId;
	}

	public void setAccountMovId(Integer accountMovId) {
		this.accountMovId = accountMovId;
	}

	public Account getAccountByAccountDestId() {
		return this.accountByAccountDestId;
	}

	public void setAccountByAccountDestId(Account accountByAccountDestId) {
		this.accountByAccountDestId = accountByAccountDestId;
	}

	public Account getAccountByAccountOriginId() {
		return this.accountByAccountOriginId;
	}

	public void setAccountByAccountOriginId(Account accountByAccountOriginId) {
		this.accountByAccountOriginId = accountByAccountOriginId;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public Timestamp getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Timestamp datetime) {
		this.datetime = datetime;
	}

}
