package modelo;
// Generated 22:38:40, 2 de feb. de 2023 by Hibernate Tools 6.1.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private Integer accountno;
	private Emp emp;
	private BigDecimal amount;
	private Set accMovementsForAccountDestId = new HashSet(0);
	private Set accMovementsForAccountOriginId = new HashSet(0);

	public Account() {
	}

	public Account(Emp emp, BigDecimal amount) {
		this.emp = emp;
		this.amount = amount;
	}

	public Account(Emp emp, BigDecimal amount, Set accMovementsForAccountDestId, Set accMovementsForAccountOriginId) {
		this.emp = emp;
		this.amount = amount;
		this.accMovementsForAccountDestId = accMovementsForAccountDestId;
		this.accMovementsForAccountOriginId = accMovementsForAccountOriginId;
	}

	public Integer getAccountno() {
		return this.accountno;
	}

	public void setAccountno(Integer accountno) {
		this.accountno = accountno;
	}

	public Emp getEmp() {
		return this.emp;
	}

	public void setEmp(Emp emp) {
		this.emp = emp;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public Set getAccMovementsForAccountDestId() {
		return this.accMovementsForAccountDestId;
	}

	public void setAccMovementsForAccountDestId(Set accMovementsForAccountDestId) {
		this.accMovementsForAccountDestId = accMovementsForAccountDestId;
	}

	public Set getAccMovementsForAccountOriginId() {
		return this.accMovementsForAccountOriginId;
	}

	public void setAccMovementsForAccountOriginId(Set accMovementsForAccountOriginId) {
		this.accMovementsForAccountOriginId = accMovementsForAccountOriginId;
	}

}
