CREATE USER people_user IDENTIFIED BY "abc123." 
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON USERS;

--TABLES PRIVILEGES
GRANT CREATE SESSION TO people_user;
GRANT CREATE TABLE TO people_user;
GRANT ALTER ANY TABLE TO people_user;
GRANT DELETE ANY TABLE TO people_user;

GRANT DROP ANY TABLE TO people_user;
GRANT INSERT ANY TABLE TO people_user;
GRANT READ ANY TABLE TO people_user;
GRANT SELECT ANY TABLE TO people_user;
GRANT UPDATE ANY TABLE TO people_user;

-- TYPES PRIVILEGES
GRANT CREATE TYPE TO people_user;
GRANT CREATE ANY TYPE TO people_user;
GRANT ALTER ANY TYPE TO people_user;
GRANT DROP ANY TYPE TO people_user;
GRANT EXECUTE ANY TYPE TO people_user;
GRANT UNDER ANY TYPE TO people_user;

-- sequences
GRANT CREATE SEQUENCE TO people_user;
GRANT CREATE ANY SEQUENCE TO people_user;
GRANT ALTER ANY SEQUENCE TO people_user;
GRANT DROP ANY SEQUENCE TO people_user;
GRANT SELECT ANY SEQUENCE TO people_user;

--PROCEDURES and FUNCTIONS
GRANT CREATE PROCEDURE TO people_user;
GRANT CREATE ANY PROCEDURE TO people_user;
GRANT ALTER ANY PROCEDURE TO people_user;
GRANT DROP ANY PROCEDURE TO people_user;
GRANT EXECUTE ANY PROCEDURE TO people_user;

